const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  CUSTOMER: {
    HOTELS: '/hotels',
    ROOM_SEARCH: '/hotels/search',
    HOTEL_DETAIL: '/hotels/:id',
    ROOM_DETAIL: '/hotels/:hotelId/rooms/:roomId',
    BOOKING: '/booking',
    PAYMENT: '/payment/:id',
    MY_BOOKINGS: '/my-bookings',
    GUEST_BOOKINGS: '/guest-bookings',
    TRANSACTIONS: '/transactions',
    TRANSACTION_DETAIL: '/transactions/:id',
    PROMOTIONS: '/promotions',
    CONTACT: '/contact',
    PROFILE: '/profile',
    REFUNDS: '/refunds',
    REFUND_DETAIL: '/refunds/:id',
    BOOKING_GUIDE: '/booking-guide',
    PARTNER_CONTACT: '/partner-contact',
    MY_BOOKING_DETAIL: '/my-bookings/:id',
    MY_BOOKING_REVIEW: '/my-bookings/:id/review',
    MY_BOOKING_REVIEW_VIEW: '/my-bookings/:id/review/view',
  },
  PARTNER: {
    LOGIN: '/partner/login',
    FORGOT_PASSWORD: '/partner/forgot-password',
    DASHBOARD: '/partner/dashboard',
    HOTELS: '/partner/hotels',
    ROOMS: '/partner/rooms',
    BOOKINGS: '/partner/bookings',
    PRICING: '/partner/pricing',
    PROMOTIONS: '/partner/promotions',
    REVIEWS: '/partner/reviews',
    FINANCE: '/partner/finance',
    FINANCE_PAYOUT_DETAIL: '/partner/finance/payouts/:thangNam',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    FORGOT_PASSWORD: '/admin/forgot-password',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    HOTELS: '/admin/hotels',
    BOOKINGS: '/admin/bookings',
    AMENITIES: '/admin/amenities',
    ROOM_TYPES: '/admin/room-types',
    REVIEWS: '/admin/reviews',
    FINANCE: '/admin/finance',
    FINANCE_PARTNER_PAYOUT_DETAIL: '/admin/finance/partner-payouts/:maDoiTac',
    REPORTS: '/admin/reports',
    REPORTS_COMPLAINTS: '/admin/reports/complaints',
    PARTNER_REQUESTS: '/admin/partner-requests',
  },
};

export default ROUTES;