const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  CUSTOMER: {
    HOTELS: '/hotels',
    ROOM_SEARCH: '/hotels/search',
    HOTEL_DETAIL: '/hotels/:id',
    ROOM_DETAIL: '/hotels/:hotelId/rooms/:roomId',
    BOOKING: '/booking',
    MY_BOOKINGS: '/my-bookings',
    PROMOTIONS: '/promotions',
    CONTACT: '/contact',
    PROFILE: '/profile',
    REFUNDS: '/refunds',
    BOOKING_GUIDE: '/booking-guide',
    PARTNER_CONTACT: '/partner-contact',
    MY_BOOKING_DETAIL: '/my-bookings/:id',
    MY_BOOKING_REVIEW: '/my-bookings/:id/review',
    MY_BOOKING_REVIEW_VIEW: '/my-bookings/:id/review/view',
  },
  PARTNER: {
    DASHBOARD: '/partner/dashboard',
    HOTELS: '/partner/hotels',
    ROOMS: '/partner/rooms',
    BOOKINGS: '/partner/bookings',
    REVIEWS: '/partner/reviews',
    FINANCE: '/partner/finance',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    HOTELS: '/admin/hotels',
    BOOKINGS: '/admin/bookings',
    AMENITIES: '/admin/amenities',
    ROOM_TYPES: '/admin/room-types',
    REVIEWS: '/admin/reviews',
    FINANCE: '/admin/finance',
    REPORTS: '/admin/reports',
    PARTNER_REQUESTS: '/admin/partner-requests',
  },
};

export default ROUTES;